// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/heartbeat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int32                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_heartbeat_proto protoreflect.FileDescriptor

const file_api_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/heartbeat.proto\x12\theartbeat\"1\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x05R\tserviceId\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2U\n" +
	"\aMonitor\x12J\n" +
	"\rSendHeartbeat\x12\x1b.heartbeat.HeartbeatRequest\x1a\x1c.heartbeat.HeartbeatResponseB4Z2github.com/nishanth-gowda/heartbeat-service/api/pbb\x06proto3"

var (
	file_api_proto_heartbeat_proto_rawDescOnce sync.Once
	file_api_proto_heartbeat_proto_rawDescData []byte
)

func file_api_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_api_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_api_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_heartbeat_proto_rawDesc), len(file_api_proto_heartbeat_proto_rawDesc)))
	})
	return file_api_proto_heartbeat_proto_rawDescData
}

var file_api_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_heartbeat_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: heartbeat.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: heartbeat.HeartbeatResponse
}
var file_api_proto_heartbeat_proto_depIdxs = []int32{
	0, // 0: heartbeat.Monitor.SendHeartbeat:input_type -> heartbeat.HeartbeatRequest
	1, // 1: heartbeat.Monitor.SendHeartbeat:output_type -> heartbeat.HeartbeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_heartbeat_proto_init() }
func file_api_proto_heartbeat_proto_init() {
	if File_api_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_heartbeat_proto_rawDesc), len(file_api_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_api_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_api_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_api_proto_heartbeat_proto = out.File
	file_api_proto_heartbeat_proto_goTypes = nil
	file_api_proto_heartbeat_proto_depIdxs = nil
}
